name: Pandoc
on:
  push:
    paths:
      - "Pandoc/**"
    branches:
      - gh-pages

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Convert with Pandoc
        uses: docker://pandoc/latex
        with:
          args: >-
            -o Pandoc/resume.pdf
            Pandoc/resume.md
      - name: Commit PDF
        uses: actions/checkout@v2
        with: # Some relative inputs of your action
          token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'Aric Gardner'
          git config --global user.email 'aricg@users.noreply.github.com'
          git add Pandoc/resume.pdf
          git commit -m "Push resume.pdf"
          git push
      - uses: actions/upload-artifact@master
        with:
          name: resume.pdf
          path: Pandoc/resume.pdf
