name: Pandoc
on:
  push:
    paths:
      - "assets/Pandoc/**"
    branches:
      - gh-pages

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Convert with Pandoc
        uses: docker://pandoc/latex
        with:
          args: >-
            -o assets/Pandoc/resume.pdf
            assets/Pandoc/resume.md
      - name: Commit PDF
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add assets/Pandoc/resume.pdf
          git commit -m "Push resume.pdf"
          git push
      - uses: actions/upload-artifact@master
        with:
          name: resume.pdf
          path: assets/Pandoc/resume.pdf
